### ISSUE TITLE
IndexOutOfBounds when parsing Canvas

### ISSUE THREAD

**Issue by Arnuh** [Brenterino/jwzlib#1]
Initially tested using v38 wz. Happens for `Mob.wz/9999999.img/info` and `Reactor.wz/9208013.img/info`

It seems to be fixed by v59 and the last version I have that it still fails on is v56.

```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:682)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271)
	at wz.io.WzMappedInputStream.readByte(WzMappedInputStream.java:58)
	at wz.io.WzInputStream.readByte(WzInputStream.java:95)
	at wz.io.WzInputStream.readBytes(WzInputStream.java:156)
	at wz.WzProperty.parseExtended(WzProperty.java:180)
	at wz.WzProperty.parse(WzProperty.java:120)
	at wz.WzProperty.parseExtended(WzProperty.java:147)
	at wz.WzProperty.parse(WzProperty.java:120)
	at wz.WzImage.parse(WzImage.java:81)
	at wz.WzImage.getChildren(WzImage.java:155)
	at wz.WzImage.getChild(WzImage.java:149)
	at wz.WzImage.getChild(WzImage.java:36)
```
[Here is a link to the git as of this error.](https://github.com/Brenterino/jwzlib/tree/009287876a5bfed1b7f0167385d2376c87e3a1ac)

And code I'm using to reproduce(only these two specific entries from what I know) and make sure to use WzVersion.BMS for v38
```
WzFile file = loadFile(Paths.get("D:\\MapleStory\\v38", "Mob.wz"), 38);
file.getChild("9999999.img").getChild("info");
file = loadFile(Paths.get("D:\\MapleStory\\v38", "Reactor.wz"), 38);
file.getChild("9208013.img").getChild("info");
```

[Download to the files tested above](https://mega.nz/#!j5xwyIQZ!kNmkvTWx3pmFHfe0V4ljf82gkZls6SvGLE7NwwYABm8)

**Comment by Arnuh** [comment]
Current fix I've tested is editing https://github.com/Brenterino/jwzlib/blob/master/src/main/java/wz/WzProperty.java#L180 to do `len - ` like it did in a previous version. Seems to work on v38 and v206 in my testings.
